package com.bitesite.stress;

import com.bitesite.dao.CategoryDao;
import com.bitesite.dao.MenuItemDao;
import com.bitesite.dao.OrderDao;
import com.bitesite.dao.OutletDao;
import com.bitesite.dao.UserDao;
import com.bitesite.dto.CheckoutResult;
import com.bitesite.dto.GatewayOrder;
import com.bitesite.model.Category;
import com.bitesite.model.MenuItem;
import com.bitesite.model.Order;
import com.bitesite.model.OrderStatus;
import com.bitesite.model.Outlet;
import com.bitesite.model.Role;
import com.bitesite.model.User;
import com.bitesite.service.OrderService;
import com.bitesite.service.PaymentGateway;
import com.bitesite.tenant.Tenant;
import com.bitesite.tenant.TenantDao;
import com.bitesite.tenant.TenantStatus;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.context.ActiveProfiles;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Many students, several colleges, all ordering at once.
 *
 * <p>Opt-in: {@code mvn -Dstress=true -Dtest=ConcurrentMultiCollegeOrderStressTest test}.
 * It seeds hundreds of rows and runs for a while, which is not something every build
 * should pay for.
 *
 * <p><b>Local, not production.</b> Production is one Burstable core with a live college on
 * it, and its own audit notes that generating load there is how you cause an outage rather
 * than find one. Nothing this test looks for needs production anyway: races, deadlocks,
 * token collisions and cross-tenant leakage all reproduce against local MySQL, and they
 * reproduce more sharply because a fast database interleaves more aggressively than a slow
 * one does.
 *
 * <p>What it is actually hunting, in order of how badly each would hurt:
 *
 * <ul>
 *   <li><b>Cross-tenant leakage under load.</b> Tenant isolation is tested serially. This
 *       asks whether it holds when four colleges are writing at once, which is when a
 *       misplaced ThreadLocal or a shared cache shows itself.
 *   <li><b>Duplicate tokens and pickup codes.</b> Both are generated by reading the
 *       database and retrying on collision, which is a check-then-act race by construction.
 *       Two students in the same college in the same millisecond is exactly the case.
 *   <li><b>Lost orders.</b> Every successful checkout must be findable afterwards.
 *   <li><b>Deadlocks.</b> Concurrent status transitions over the same rows.
 * </ul>
 */
@SpringBootTest
@ActiveProfiles("test")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@EnabledIfSystemProperty(named = "stress", matches = "true")
class ConcurrentMultiCollegeOrderStressTest {

    /* Dial with -Dstress.students=N etc. The defaults are deliberately past the point
       where token collisions stop being hypothetical: tokens are BITE-1000..BITE-9999,
       so 9,000 slots per college per day. By the birthday bound, 300 orders in one
       college gives roughly a 99% chance that at least two students draw the same
       number, which is the whole point of pointing this at one college at a time. */
    private static final int COLLEGES = Integer.getInteger("stress.colleges", 4);
    private static final int OUTLETS_PER_COLLEGE = Integer.getInteger("stress.outlets", 2);
    private static final int STUDENTS_PER_COLLEGE = Integer.getInteger("stress.students", 300);
    private static final int THREADS = Integer.getInteger("stress.threads", 64);

    /** Real Razorpay is never involved. Thread-safe and instant, so the database is the
     *  only thing under contention rather than a mock's own locking. */
    @TestConfiguration
    static class StubGateway {
        @Bean
        @Primary
        PaymentGateway stubPaymentGateway() {
            return new PaymentGateway() {
                private final AtomicInteger seq = new AtomicInteger();
                /* Globally unique, not just unique within this run. payments has a unique
                   constraint on the gateway order id, and a counter starting at 1 every run
                   collides with the rows the previous run left behind — which shows up as
                   124 DuplicateKeyExceptions that look exactly like an application race
                   until you read the constraint name. */
                private final String prefix = "stub_" + UUID.randomUUID().toString().substring(0, 8) + "_";

                @Override
                public GatewayOrder createOrder(BigDecimal amountRupees, String receipt) {
                    return new GatewayOrder(prefix + seq.incrementAndGet(), "stub_key",
                            amountRupees.multiply(BigDecimal.valueOf(100)).longValue(), "INR");
                }

                @Override
                public boolean verifyPaymentSignature(String o, String p, String s) {
                    return true;
                }

                @Override
                public boolean verifyWebhookSignature(String payload, String header) {
                    return true;
                }

                @Override
                public void refund(String gatewayPaymentId, BigDecimal amountRupees) {
                    // no-op: nothing in this test cancels
                }
            };
        }
    }

    @Autowired private TenantDao tenantDao;
    @Autowired private OutletDao outletDao;
    @Autowired private UserDao userDao;
    @Autowired private MenuItemDao menuItemDao;
    @Autowired private CategoryDao categoryDao;
    @Autowired private OrderDao orderDao;
    @Autowired private OrderService orderService;
    @Autowired private PasswordEncoder passwordEncoder;
    @Autowired private JdbcTemplate jdbcTemplate;

    private record Campus(Long tenantId, List<Long> outletIds, List<Long> studentIds,
                          Map<Long, List<Long>> menuByOutlet) {}

    private final List<Campus> campuses = new ArrayList<>();
    private String runId;

    @BeforeAll
    void seedFourColleges() {
        runId = UUID.randomUUID().toString().substring(0, 6);
        for (int c = 0; c < COLLEGES; c++) {
            Tenant tenant = tenantDao.save(Tenant.builder()
                    .name("Stress College " + runId + "-" + c).status(TenantStatus.ACTIVE).build());

            List<Long> outlets = new ArrayList<>();
            Map<Long, List<Long>> menuByOutlet = new HashMap<>();
            for (int o = 0; o < OUTLETS_PER_COLLEGE; o++) {
                Outlet outlet = outletDao.save(Outlet.builder().tenantId(tenant.getId())
                        .name("Canteen " + c + "-" + o).active(true).build());
                outlets.add(outlet.getId());

                Long categoryId = categoryDao.save(Category.builder()
                        .tenantId(tenant.getId()).outletId(outlet.getId())
                        .name("Snacks").sortOrder(0).build()).getId();

                List<Long> items = new ArrayList<>();
                for (int m = 0; m < 5; m++) {
                    items.add(menuItemDao.save(MenuItem.builder()
                            .tenantId(tenant.getId()).outletId(outlet.getId())
                            .name("Item " + c + "-" + o + "-" + m).categoryId(categoryId)
                            .price(new BigDecimal("30.00")).available(true).build()).getId());
                }
                menuByOutlet.put(outlet.getId(), items);
            }

            List<Long> students = new ArrayList<>();
            for (int s = 0; s < STUDENTS_PER_COLLEGE; s++) {
                students.add(userDao.save(User.builder().tenantId(tenant.getId())
                        .name("S" + c + "-" + s)
                        .email("stress-" + runId + "-" + c + "-" + s + "@test.local")
                        .passwordHash(passwordEncoder.encode("x"))
                        .role(Role.USER).activeRole(Role.USER).active(true).build()).getId());
            }
            campuses.add(new Campus(tenant.getId(), outlets, students, menuByOutlet));
        }
    }

    @Test
    void hundredsOfStudentsOrderingAtOnceAcrossCollegesStaysCorrect() throws Exception {
        int expected = COLLEGES * STUDENTS_PER_COLLEGE;
        ExecutorService pool = Executors.newFixedThreadPool(THREADS);
        CountDownLatch start = new CountDownLatch(1);
        CountDownLatch done = new CountDownLatch(expected);
        ConcurrentLinkedQueue<String> failures = new ConcurrentLinkedQueue<>();
        ConcurrentLinkedQueue<Long> placed = new ConcurrentLinkedQueue<>();

        for (Campus campus : campuses) {
            for (Long studentId : campus.studentIds()) {
                pool.submit(() -> {
                    try {
                        // Every thread waits here, so the whole cohort hits the database in
                        // the same instant rather than politely spreading itself out.
                        start.await();

                        Long outletId = campus.outletIds()
                                .get(Math.floorMod(studentId.intValue(), campus.outletIds().size()));
                        Map<Long, Integer> cart = new HashMap<>();
                        List<Long> menu = campus.menuByOutlet().get(outletId);
                        cart.put(menu.get(Math.floorMod(studentId.intValue(), menu.size())), 2);
                        cart.put(menu.get(Math.floorMod(studentId.intValue() + 1, menu.size())), 1);

                        CheckoutResult result =
                                orderService.checkout(campus.tenantId(), outletId, studentId, cart);
                        orderService.confirmPayment(result.gatewayOrder().gatewayOrderId(),
                                "stub_pay_" + result.order().getId(), "sig");
                        placed.add(result.order().getId());
                    } catch (Exception e) {
                        failures.add(e.getClass().getSimpleName() + ": " + e.getMessage());
                    } finally {
                        done.countDown();
                    }
                });
            }
        }

        long began = System.nanoTime();
        start.countDown();
        boolean finished = done.await(5, TimeUnit.MINUTES);
        long millis = (System.nanoTime() - began) / 1_000_000;
        pool.shutdownNow();

        System.out.printf("%n[stress] %d concurrent checkouts across %d colleges in %d ms (%.1f/s)%n",
                expected, COLLEGES, millis, expected * 1000.0 / Math.max(millis, 1));
        if (!failures.isEmpty()) {
            System.out.println("[stress] failures: " + failures.size());
            failures.stream().limit(10).forEach(f -> System.out.println("   " + f));
        }

        assertThat(finished).as("the run did not finish inside five minutes").isTrue();
        assertThat(failures).as("checkouts threw under concurrency").isEmpty();
        assertThat(placed).as("every checkout should have produced an order").hasSize(expected);

        // ---- every order landed, and in the right college ----
        for (Campus campus : campuses) {
            Integer paid = jdbcTemplate.queryForObject(
                    "SELECT COUNT(*) FROM orders WHERE tenant_id = ? AND status = 'PAID'",
                    Integer.class, campus.tenantId());
            assertThat(paid)
                    .as("college %s lost paid orders", campus.tenantId())
                    .isEqualTo(STUDENTS_PER_COLLEGE);

            Integer strays = jdbcTemplate.queryForObject(
                    "SELECT COUNT(*) FROM orders o JOIN users u ON u.id = o.user_id "
                            + "WHERE o.tenant_id = ? AND u.tenant_id <> o.tenant_id",
                    Integer.class, campus.tenantId());
            assertThat(strays)
                    .as("an order was written into a college its student does not belong to")
                    .isZero();
        }
    }

    /**
     * Tokens are generated by reading the database and retrying on collision, which is a
     * check-then-act race. Under a burst of same-college checkouts it is the most likely
     * thing in the product to hand two students the same number to collect by.
     */
    @Test
    void noTwoOrdersInACollegeShareATokenOnTheSameDay() {
        for (Campus campus : campuses) {
            Integer duplicates = jdbcTemplate.queryForObject(
                    "SELECT COUNT(*) FROM (SELECT token_no FROM orders WHERE tenant_id = ? "
                            + "GROUP BY token_no, DATE(created_at) HAVING COUNT(*) > 1) d",
                    Integer.class, campus.tenantId());
            assertThat(duplicates)
                    .as("two orders in college %s share a token on the same day", campus.tenantId())
                    .isZero();
        }
    }

    /** Staff moving many orders through the lifecycle at once must not deadlock or drop any. */
    @Test
    void staffCanDriveTheWholeQueueThroughTheLifecycleConcurrently() throws Exception {
        List<Order> paid = new ArrayList<>();
        for (Campus campus : campuses) {
            for (Long outletId : campus.outletIds()) {
                paid.addAll(orderDao.findByOutlet(campus.tenantId(), outletId, OrderStatus.PAID, 500, 0));
            }
        }
        assertThat(paid).as("nothing to drive through the lifecycle").isNotEmpty();

        ExecutorService pool = Executors.newFixedThreadPool(THREADS);
        CountDownLatch start = new CountDownLatch(1);
        CountDownLatch done = new CountDownLatch(paid.size());
        ConcurrentLinkedQueue<String> failures = new ConcurrentLinkedQueue<>();

        for (Order order : paid) {
            pool.submit(() -> {
                try {
                    start.await();
                    orderService.advanceStatus(order.getId(), order.getTenantId(), OrderStatus.PREPARING, null);
                    orderService.advanceStatus(order.getId(), order.getTenantId(), OrderStatus.READY_FOR_PICKUP, null);
                } catch (Exception e) {
                    failures.add(e.getClass().getSimpleName() + ": " + e.getMessage());
                } finally {
                    done.countDown();
                }
            });
        }
        start.countDown();
        boolean finished = done.await(5, TimeUnit.MINUTES);
        pool.shutdownNow();

        if (!failures.isEmpty()) {
            System.out.println("[stress] lifecycle failures: " + failures.size());
            failures.stream().limit(10).forEach(f -> System.out.println("   " + f));
        }
        assertThat(finished).as("lifecycle run did not finish in time").isTrue();
        assertThat(failures).as("status transitions threw under concurrency").isEmpty();

        // Pickup codes are issued at READY_FOR_PICKUP and must be unique per outlet while live.
        for (Campus campus : campuses) {
            for (Long outletId : campus.outletIds()) {
                Integer dupes = jdbcTemplate.queryForObject(
                        "SELECT COUNT(*) FROM (SELECT pickup_code FROM orders "
                                + "WHERE outlet_id = ? AND pickup_code IS NOT NULL "
                                + "AND status = 'READY_FOR_PICKUP' "
                                + "GROUP BY pickup_code HAVING COUNT(*) > 1) d",
                        Integer.class, outletId);
                assertThat(dupes)
                        .as("two live orders at outlet %s share a pickup code", outletId)
                        .isZero();
            }
        }
    }
}
