package com.bitesite.web;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * The pages link one stylesheet, {@code css/app-bundle.css}, which is generated by
 * {@code scripts/build-css-bundle.py} from {@code css/parts/*.css}. The parts are the
 * editable source; the bundle is the artefact.
 *
 * <p>That arrangement has one failure mode and it is silent: edit a part, forget to
 * regenerate, and the change simply never reaches a browser. Nothing else in the build
 * would notice — the part is still on disk, still valid CSS, still in the jar, just no
 * longer linked by anything. This test is the thing that notices.
 *
 * <p>It also guards the property that makes bundling safe at all. Each part's header says
 * the load order IS the cascade, and concatenation preserves that only while no part
 * introduces an {@code @import} or {@code @charset} (both legal only at the top of a
 * stylesheet, so every one after the first would be dropped) or a relative {@code url()}
 * (which resolves against the stylesheet's own URL, and the bundle sits one directory up
 * from the parts).
 */
class CssBundleTest {

    /** Cascade order. Changing this list means changing which rules win. */
    private static final List<String> PARTS = List.of(
            "01-tokens", "02-base", "03-customer", "04-auth", "05-shared",
            "06-editorial", "07-brutalist", "08-customer-final", "09-console");

    private static final Path CSS = Path.of("src/main/resources/static/css");

    private static final String HEADER = """
            /* GENERATED FILE — DO NOT EDIT.
               Concatenation of css/parts/*.css in cascade order, built by
               scripts/build-css-bundle.py and pinned by CssBundleTest.
               Edit the parts; regenerate this. */
            """;

    private static String read(Path p) throws IOException {
        return Files.readString(p, StandardCharsets.UTF_8);
    }

    /** Exactly what the build script writes, rebuilt here from the same inputs. */
    private static String expectedBundle() throws IOException {
        StringBuilder sb = new StringBuilder(HEADER);
        for (int i = 0; i < PARTS.size(); i++) {
            if (i > 0) {
                sb.append('\n');
            }
            sb.append("/* ==== ").append(PARTS.get(i)).append(".css ==== */\n")
              .append(read(CSS.resolve("parts/" + PARTS.get(i) + ".css")).stripTrailing())
              .append('\n');
        }
        return sb.toString();
    }

    @Test
    void theBundleMatchesThePartsItIsBuiltFrom() throws IOException {
        assertThat(read(CSS.resolve("app-bundle.css")))
                .as("css/app-bundle.css is stale — a part was edited without rebuilding it, "
                        + "so that change is not reaching any browser. Run: "
                        + "python3 scripts/build-css-bundle.py")
                .isEqualTo(expectedBundle());
    }

    /**
     * Concatenation only preserves the cascade while these stay absent. See the class
     * comment; the failure from an {@code @import} in part 5 would be that parts 6 to 9
     * stop applying, which is not a subtle bug but is a very confusing one.
     */
    @Test
    void noPartUsesAConstructThatConcatenationWouldBreak() throws IOException {
        for (String part : PARTS) {
            String css = read(CSS.resolve("parts/" + part + ".css"));
            assertThat(css)
                    .as("%s.css must not use @import — only legal at the top of a stylesheet, "
                            + "so bundling would silently drop it and everything after it", part)
                    .doesNotContain("@import");
            assertThat(css)
                    .as("%s.css must not use @charset, for the same reason", part)
                    .doesNotContain("@charset");
        }
    }

    /**
     * A relative url() resolves against the stylesheet's own address. The parts live in
     * /css/parts/ and the bundle in /css/, so a relative reference that worked in a part
     * would point one directory too high once bundled.
     */
    @Test
    void everyAssetReferenceIsRootRelativeOrInline() throws IOException {
        var offenders = new java.util.ArrayList<String>();
        var url = java.util.regex.Pattern.compile("url\\(\\s*['\"]?([^'\")]+)");
        // Inlined SVG carries its own url(#filter) references, and those resolve inside the
        // data URI rather than against the stylesheet, so they are not what this is looking
        // for. 07-brutalist.css has one — a noise texture — and scanning into it reports a
        // relative reference that does not exist.
        var dataUri = java.util.regex.Pattern.compile("url\\(\\s*['\"]?data:[^)]*\\)");
        for (String part : PARTS) {
            String css = dataUri.matcher(read(CSS.resolve("parts/" + part + ".css")))
                    .replaceAll("url(data:elided)");
            var m = url.matcher(css);
            while (m.find()) {
                String ref = m.group(1).trim();
                if (!ref.startsWith("/") && !ref.startsWith("data:") && !ref.startsWith("#")
                        && !ref.startsWith("http")) {
                    offenders.add(part + ".css -> " + ref);
                }
            }
        }
        assertThat(offenders)
                .as("these url() references are relative, so they resolve differently in the "
                        + "bundle than in the part. Make them root-relative (/img/...).")
                .isEmpty();
    }
}
